apiVersion: v1
kind: Service
metadata:
  name: {{ include "phoenix.fullname" . }}
  labels:
    {{- include "phoenix.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "phoenix.selectorLabels" . | nindent 4 }}
